feat: BoN 등록, 삭제, 댓글 등록,삭제, like 기능
swyp-fade/fade-api pull request #155
Opened 2024-09-15 16:30 UTC by n4oah

2024-09-17 13:38 UTC, Junobee25 requested changes

2024-09-17 13:38 UTC, Junobee25 commented on src/main/java/com/fade/bon/dto/response/CreateBonResDto.java
> +public record CreateBonResDto(
Dto 네이밍은 빼고 Res로 끝나게 나머지랑 통일하명 좋을거 같습니다!

2024-09-17 13:38 UTC, Junobee25 commented on src/main/java/com/fade/bon/dto/request/CreateBonReqDto.java
> +public record CreateBonReqDto (
Dto 네이밍은 빼고 Req로 끝나게 나머지랑 통일하면 좋을거 같습니다!

2024-09-17 13:38 UTC, Junobee25 commented on src/main/java/com/fade/bon/service/BonService.java
> +@Transactional(readOnly = true)
클래스에 붙혀두신 이유가 궁금합니다!

2024-09-17 14:39 UTC, n4oah commented on src/main/java/com/fade/bon/service/BonService.java
> +@Transactional(readOnly = true)
@Transactional(readOnly = true)
이거 말씀하시는 건가요 ?

사실 저도 크게 생각없이 대부분의 경우 붙이는 걸로 알고 있어서 붙였던게 전부였던 것 같아서
좀 찾아봤는데
https://hungseong.tistory.com/74

OSIV가 제일 큰 이유인 것 같아요.

아마 저희는 OSIV가 true로 되어 있어서 사실 붙이든 안 붙이든 상관은 없을 것 같은데, OSIV를 꺼두고 조회용 service에 Transactional readonly를 전부 사용하는 게 나을 것 같습니다 !

2024-09-18 00:48 UTC, Junobee25 approved these changes
고생하셨습니다!

2024-09-18 01:49 UTC, merged