feat: #44 투표 내역 No-offset 스크롤 서비스 로직 구현
swyp-fade/fade-api pull request #47
Opened 2024-07-21 08:58 UTC by Junobee25

#44

2024-07-21 17:44 UTC, n4oah requested changes

2024-07-21 17:44 UTC, n4oah commented on src/main/java/com/fade/vote/service/VoteService.java
> +        return new VoteResultResponse(voteResult, calculateLastCursor(voteResult, type));
이 메서드 호출하는 API가 없는 것 같습니다.
그리고 단순 select라 Transaction readonly로 해도 될 것 같습니다.

그리고 type은 어떤건가요?

2024-07-21 17:53 UTC, Junobee25 commented on src/main/java/com/fade/vote/service/VoteService.java
> +        return new VoteResultResponse(voteResult, calculateLastCursor(voteResult, type));
API는 코드 수정 후 추가해서 PR에 올리겠습니다!

Type은 다음과 같습니다(프론트 측 요구사항입니다)
0 : 다운 스크롤(이전 날짜 투표 내역 조회)
1 : 업 스크롤(이후 날짜 투표 내역조회)
2 : 날짜 선택 시 이전 이후 3일씩 붙혀서 오늘 포함 7일 데이터 반환

마지막 스크롤 커서에 대한 response 추가하면 완료될거 같습니다

2024-07-22 05:05 UTC, n4oah approved these changes
고생하셨습니다 !

2024-07-22 05:11 UTC, merged